### PR TITLE
FR translation

### PR DESCRIPTION
**Pull request by trebmuh**
French translation.
Please let me know if anything else is required/missing.

BTW : well done for this useful website.

### CODE REVIEW

**Comment by trebmuh** [comment]
Mmm, that failed check seems to suggest that the `'` character needs to be escated in some way. Any hint on that @lfzawacki ?

**Comment by lfzawacki** [comment]
I'm gonna try it locally and give you some feedback ASAP.

**Comment by trebmuh** [comment]
Thanks, let me know how it goes.

**Comment by lfzawacki** [comment]
Merged and deployed to the website. There were a few keys missing like, artifacts.artifact_links.mirrors and some stuff in info.about, but other than that it looks REALLY good :)

Thank you so much for your help on this translation!

**Comment by trebmuh** [comment]
Hi, and thanks for that.
I'm happy if it is helping since this website is a great addition to the free software community.

Quick (auto-focused) question : I saw that you credited me on https://github.com/lfzawacki/musical-artifacts , thanks for that. Are the translators mentioned somewhere on the web interface too?

Other than this selfish question, I'll certainly will be browsing the website a bit on the next days to track some mistakes I might have let go unnoticed. So I'll certainly make another pull request on the days coming to fix those potential typos/mistakes.

You look (or I might not understood) to suggest that some translations are not done. Since I started to translate the FR files from the EN ones, would that mean that they're missing for the EN files in config/locales/* ?

**Comment by lfzawacki** [comment]
Thanks for the compliments.

Translators are not mentioned on the web page right now, we probably should
have a 'Credits' page somewhere on the interface but there's not right now.

The thing about the missing translations is that when the translation key
is called 'Contact' it'll be right in english even if it's missing. So due
to my laziness some of these keys are missing in english... When they're
rendered on the interface you'll be able to see a tooltip with 'translation
missing: fr.info.about.access' and this can help you find the missing keys.

In the future I'll look into putting all the missing keys into the english
translation.

**Comment by trebmuh** [comment]
> When they're rendered on the interface you'll be able to see a tooltip with 'translation missing: fr.info.about.access' and this can help you find the missing keys.

Do I need to be logged to see this tooltip ? Becaiuse looking at here : https://musical-artifacts.com/info/about#access , where "ACCESS" isn't translated, I can't see any tooltip.

I'm happy to help to add the missing key. Is that just a matter of putting them into the yml files or does it need to be indicated as "translatable" into the source code as well ?

**Comment by lfzawacki** [comment]
This is what I mean by tooltip, it should appear even if logged out.
selection_004

The string is marked as translatable when it's included on the code using the Internationalization method, see here this example https://github.com/lfzawacki/musical-artifacts/blob/master/app/views/info/about.html.haml#L44

In this case the `t('.access')` inside `app/views/info/about.html.haml` means the keys will be called `info.about.access`. Hope that helps.

**Comment by trebmuh** [comment]
OK, got it now. Thanks.
I'll do a review (on tomorrow or this week end) about what's already translated, and try to add the missing parts into the EN yml file. Then I'll send a pull request.

**Pull request merged**
