### PR TITLE
Update French translation.

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by trebmuh** [comment]
ping @lfzawacki :)

**Comment by lfzawacki** [comment]
Sorry for the delay in answering, I'll have some time to look into this tomorrow and then I can merge it. Meanwhile you could look into the translation of the new/edit artifact page, which I've made some changes and is now not 100% in french also.

**Comment by lfzawacki** [comment]
Merged and deployed, thanks and sorry for the delay!

**Comment by trebmuh** [comment]
Thank you. I'll try to find some time to review the other changes you mentioned.

**Pull request merged**
